export default {
  DEFAULT_TOKEN_LIST_URL:
    'ipfs://QmZbWsMTSGqPny7jSzbMX43RaAvUupKHsHiRAZU9hJ75WB',
  CONTRACT_ADDRESS: {
    TREASURE_BAY_FACTORY: process.env.TREASURE_BAY_FACTORY_CONTRACT_ADDRESS,
    OBAY_TOKEN: process.env.OBAY_TOKEN_CONTRACT_ADDRESS,
    OBAY_TREASURY: process.env.OBAY_TREASURY_CONTRACT_ADDRESS,
  },
  PINATA: {
    GATEWAY_URL: process.env.PINATA_GATEWAY_URL,
    API_KEY: process.env.PINATA_API_KEY,
    API_SECRET: process.env.PINATA_API_SECRET,
    API_JWT_TOKEN: process.env.PINATA_API_JWT_TOKEN,
  },
  DEFI_PULSE_DATA: {
    API_KEY: process.env.DEFI_PULSE_DATA_API_KEY,
  },
};
